# Generated by Django 4.1.7 on 2023-03-14 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])),
                ('work_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Invalid work ID.')])),
                ('phone', models.CharField(max_length=11)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('expected_arrival_time', models.DateTimeField()),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('carrier_id', models.CharField(max_length=10)),
                ('vehicle_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('未完成', '未完成'), ('进行中', '进行中'), ('已完成', '已完成'), ('已取消', '已取消')], max_length=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_missions', to='mapProjectApp.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_missions', to='mapProjectApp.location')),
            ],
        ),
        migrations.CreateModel(
            name='MissionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapProjectApp.location')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapProjectApp.mission')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='path',
            field=models.ManyToManyField(through='mapProjectApp.MissionPath', to='mapProjectApp.location'),
        ),
    ]
